spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Servicio de Usuarios
        - id: usuario-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuarios/**

        # 2. Servicio de Autenticaci√≥n
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

        # 3. Servicio de Noticias
        - id: noticia-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/noticias/**

        - id: noticia-uploads
          uri: http://localhost:8083
          predicates:
            - Path=/uploads/noticias/**

        # 4. Servicio de Productos
        - id: producto-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/productos/**

        - id: producto-uploads
          uri: http://localhost:8084
          predicates:
            - Path=/uploads/productos/**

        # 5. Servicio de Compras
        - id: compra-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/compras/**

        # 6. Servicio de Partidos
        - id: partido-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/partidos/**
        
        # Servicio de Ligas (dentro del microservicio de partidos)
        - id: liga-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/ligas/**

        # Servicio de Jornadas (dentro del microservicio de partidos)
        - id: jornada-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/jornadas/**

        # 7. Servicio de Equipos
        - id: equipo-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/equipos/**

        - id: equipo-uploads
          uri: http://localhost:8087
          predicates:
            - Path=/uploads/equipos/**

server:
  port: 8080

logging:
  level:
    "[org.springframework.cloud.gateway]": ERROR
    "[org.springframework.web]": ERROR